language: go

go:
        - 1.5
install:
        - export TRAVIS_BUILD_DIR=$HOME/gopath
        - export GOPATH=${TRAVIS_BUILD_DIR}/src
        - echo $GOPATH
        - cd $GOPATH
script: go test -v github.com/tenaciousjzh/ballclock/..